#!/usr/bin/env bash
#install nginx, config port and file

sudo apt update
sudo apt -y install nginx
#sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School for the win!" > /var/www/html/index.html
sudo /etc/init.d/nginx start