#!/usr/bin/env bash
#change text in file

sudo apt-get update
sudo apt-get install nginx
echo "Holberton School" > /var/www/html/index.html

new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-available/default
service nginx restart