#!/usr/bin/env bash
# Install the load balanecer

apt-get -y update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg .
cat >> /etc/haproxy/haproxy.cfg << EOF
frontend front
	bind *:80
	mode http
	default_backend back
backend back
    balance roundrobin
    server 1665-web-01 34.75.26.100:80 check
    server 1665-web-02 35.237.221.251:80 check
EOF
service haproxy restart