#!/usr/bin/env bash
# Bash create file with your process and kill

sudo touch /var/run/holbertonscript.pid
sudo bash -c "echo $$ > /var/run/holbertonscript.pid"

function sigterm {
    echo "I hate the kill command"
    sudo rm /var/run/holbertonscript.pid
}
function sigquit {
    sudo rm /var/run/holbertonscript.pid
}
function sigint {
    echo "Y U no love me?!"
}

trap sigint SIGINT
trap sigquit SIGQUIT
trap sigterm SIGTERM


while true
do
	echo "To infinity and beyond indefinitely"
done