#!/usr/bin/env bash
# This script is displaying fizzbuzz

i=1
while [ $i -lt 100 ]
do
    if (( i % 3 == 0  &&  i % 5 == 0 ))
    then
        echo "FizzBuzz"
    elif (( i % 3 == 0 ))
    then
        echo "Fizz"
    elif (( i % 5 == 0 ))
    then
        echo "Buzz"
    else
        echo "$i"
    fi
    ((i++))
done