#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

i=1

while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad look"
    elif [ $i -eq 8 ]
    then
        echo "good look"
    else
        echo "Holberton School"
    fi

    ((i++))
done