#!/usr/bin/env bash
# change the ip facebook and loclahost

cp /etc/hosts ~/hosts.new
sed -i "/127.0.0.2/c\127.0.0.1" ~/hosts.new
sed -i "2i8.8.8.8 facebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
